-- MySQL Script generated by MySQL Workbench
-- Mon Jan 31 23:48:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `salarioBase` DECIMAL(19,4) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `admissao` DATE NOT NULL,
  `funcionarioMes` TINYINT NOT NULL,
  `faltas` INT NOT NULL,
  `tipoBonus` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionarioSalario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionarioSalario` (
  `idFuncionarioSalario` INT NOT NULL AUTO_INCREMENT,
  `idFuncionario` INT NOT NULL,
  `dataCalculo` DATE NOT NULL,
  `salarioBase` DECIMAL(19,4) NOT NULL,
  `bonus` DECIMAL(19,4) NOT NULL,
  `salarioTotal` DECIMAL(19,4) NOT NULL,
  PRIMARY KEY (`idFuncionarioSalario`),
  INDEX `fk_FuncionarioSalario_funcionario_idx` (`idFuncionario` ASC) VISIBLE,
  CONSTRAINT `fk_FuncionarioSalario_funcionario`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `mydb`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionarioBonus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionarioBonus` (
  `idfuncionarioBonus` INT NOT NULL AUTO_INCREMENT,
  `idFuncionario` INT NOT NULL,
  `dataCalculo` DATE NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `tipoBonus` VARCHAR(45) NOT NULL,
  `valorBonus` DECIMAL(19,4) NOT NULL,
  PRIMARY KEY (`idfuncionarioBonus`),
  INDEX `fk_funcionarioBonus_funcionario1_idx` (`idFuncionario` ASC) VISIBLE,
  CONSTRAINT `fk_funcionarioBonus_funcionario1`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `mydb`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



//select da tabela de salario
select f.nome, fs.dataCalculo, fs.salarioBase, fs.bonus, fs.salarioTotal from funcionario f left join funcionari
oSalario fs on f.id = fs.idFuncionario;

//insert na tabela de salario
insert into funcionarioSalario(idFuncionario, dataCalculo, salarioBase, bonus, salarioTotal) values (1, datetime('now'), 1000, 30, 1030)
