/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.gestaodefuncionarios.view;

import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author Rafael
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        pInferior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblVersao = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNumFuncionarios = new javax.swing.JLabel();
        lblLogFormat = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuFuncionario = new javax.swing.JMenu();
        btnNovo = new javax.swing.JMenuItem();
        btnBuscar = new javax.swing.JMenuItem();
        btnFechar = new javax.swing.JMenuItem();
        menuSalario = new javax.swing.JMenu();
        btnCalcular = new javax.swing.JMenuItem();
        menuFerramentas = new javax.swing.JMenu();
        btnConfiguracoes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestão de Funcionários");
        setBackground(new java.awt.Color(238, 238, 238));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/people-48.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desktopPane.setBackground(new java.awt.Color(164, 214, 191));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(desktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 480));

        pInferior.setBackground(new java.awt.Color(255, 255, 255));
        pInferior.setForeground(new java.awt.Color(255, 255, 255));
        pInferior.setFocusable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/versao-50.png"))); // NOI18N
        jLabel1.setLabelFor(lblVersao);

        lblVersao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblVersao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVersao.setText("0");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/people-50.png"))); // NOI18N
        jLabel2.setLabelFor(lblNumFuncionarios);

        lblNumFuncionarios.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNumFuncionarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumFuncionarios.setText("0");

        lblLogFormat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/help-48.png"))); // NOI18N

        javax.swing.GroupLayout pInferiorLayout = new javax.swing.GroupLayout(pInferior);
        pInferior.setLayout(pInferiorLayout);
        pInferiorLayout.setHorizontalGroup(
            pInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInferiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVersao, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                .addGap(445, 445, 445)
                .addComponent(lblLogFormat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        pInferiorLayout.setVerticalGroup(
            pInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInferiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInferiorLayout.createSequentialGroup()
                        .addGroup(pInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pInferiorLayout.createSequentialGroup()
                                .addComponent(lblLogFormat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInferiorLayout.createSequentialGroup()
                        .addComponent(lblNumFuncionarios)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInferiorLayout.createSequentialGroup()
                        .addComponent(lblVersao)
                        .addGap(20, 20, 20))))
        );

        getContentPane().add(pInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 1110, 70));

        menuBar.setBorder(null);

        menuFuncionario.setMnemonic('f');
        menuFuncionario.setText("Funcionários");
        menuFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnNovo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-user-24.png"))); // NOI18N
        btnNovo.setMnemonic('o');
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        menuFuncionario.add(btnNovo);

        btnBuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search-24.png"))); // NOI18N
        btnBuscar.setMnemonic('s');
        btnBuscar.setText("Buscar");
        menuFuncionario.add(btnBuscar);

        btnFechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btnFechar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnFechar.setMnemonic('x');
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        menuFuncionario.add(btnFechar);

        menuBar.add(menuFuncionario);

        menuSalario.setText("Salário");
        menuSalario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnCalcular.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnCalcular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cheap-24.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        menuSalario.add(btnCalcular);

        menuBar.add(menuSalario);

        menuFerramentas.setMnemonic('h');
        menuFerramentas.setText("Ferramentas");
        menuFerramentas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnConfiguracoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnConfiguracoes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gear-24.png"))); // NOI18N
        btnConfiguracoes.setMnemonic('c');
        btnConfiguracoes.setText("Configurações");
        menuFerramentas.add(btnConfiguracoes);

        menuBar.add(menuFerramentas);

        setJMenuBar(menuBar);

        setSize(new java.awt.Dimension(1125, 614));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed

    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnBuscar;
    private javax.swing.JMenuItem btnCalcular;
    private javax.swing.JMenuItem btnConfiguracoes;
    private javax.swing.JMenuItem btnFechar;
    private javax.swing.JMenuItem btnNovo;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblLogFormat;
    private javax.swing.JLabel lblNumFuncionarios;
    private javax.swing.JLabel lblVersao;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFerramentas;
    private javax.swing.JMenu menuFuncionario;
    private javax.swing.JMenu menuSalario;
    private javax.swing.JPanel pInferior;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getBtnFechar() {
        return btnFechar;
    }

    public JMenuItem getBtnNovo() {
        return btnNovo;
    }
    
    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    public JMenuItem getBtnBuscar() {
        return btnBuscar;
    }

    public JMenuItem getBtnCalcular() {
        return btnCalcular;
    }

    public JLabel getLblNumFuncionarios() {
        return lblNumFuncionarios;
    }

    public JMenuItem getBtnConfiguracoes() {
        return btnConfiguracoes;
    }

    public JLabel getLblVersao() {
        return lblVersao;
    }

    public JLabel getLblLogFormat() {
        return lblLogFormat;
    }

}
